[workspace]
members = [
    'chainbridge',
    'example-erc721',
    'example-pallet',
    'substrate-node-template/node',
    'substrate-node-template/pallets/template',
    'substrate-node-template/runtime',
]
[profile.release]
panic = 'unwind'
